stages:
  - dockerimage
  - package
  - submit_qa
  - submit_production
  
variables:
  DOCKER_IMAGE: docker-0.2.1
  
before_script:
  - if [[ "$CI_COMMIT_TAG" == rpm-* ]] ; then export RPM_VERSION=${CI_COMMIT_TAG#rpm-}; else export RPM_VERSION=test${CI_PIPELINE_ID}git${CI_COMMIT_SHA:0:8}; fi
  
create_dockerimage:
  stage: dockerimage
  only:
    - /^docker-.*$/
  tags:
    - docker-image-build
  script:
    - ""
  variables:
    TO: gitlab-registry.cern.ch/tapeanalytics/exdemon:$CI_COMMIT_TAG
    DOCKER_LOGIN_SERVER: gitlab-registry.cern.ch
  # DOCKER_LOGIN_USERNAME and DOCKER_LOGIN_PASSWORD should be provided as secure variables from gitlab web interface
  
exdemon_package:
  stage: package
  image: gitlab-registry.cern.ch/tapeanalytics/exdemon:$DOCKER_IMAGE
  script:
    - mvn versions:set -DnewVersion=$RPM_VERSION
    - mvn clean test package
  artifacts:
    expire_in: 30 days
    paths:
      - target/
    
submit_qa:
  stage: submit_qa
  image: gitlab-registry.cern.ch/db/cerndb-infra-hadoop-conf:hadoop-config-playground
  only:
    - /^release-.*$/
  when: manual
  script:
    - hadoop-set-default-conf.sh hadoop-qa
    - echo $SUBMIT_PASS | kinit $SUBMIT_USER
    - cp target/exdemon-* lib/
    - yum -y install lib/zookeepercli-1.0.12-1.x86_64.rpm
    - sed -i s/\<environment\>/qa/g conf/exdemon.properties
    - sed -i s/\<exdemon_password\>/$EXDEMON_PASS/g conf/exdemon.properties
    - bin/restart
  dependencies:
    - exdemon_package
    
submit_production:
  stage: submit_production
  image: gitlab-registry.cern.ch/db/cerndb-infra-hadoop-conf:hadoop-config-playground
  only:
    - /^release-.*$/
  when: manual
  script:
    - hadoop-set-default-conf.sh analytix
    - echo $SUBMIT_PASS | kinit $SUBMIT_USER
    - cp target/exdemon-* lib/
    - yum -y install lib/zookeepercli-1.0.12-1.x86_64.rpm
    - sed -i s/\<environment\>/production/g conf/exdemon.properties
    - sed -i s/\<exdemon_password\>/$EXDEMON_PASS/g conf/exdemon.properties
    - bin/restart
  dependencies:
    - submit_qa
    - exdemon_package